server:
   port: 8082
   servlet:
      context-path: /userservice
logging:
   level:
      root: INFO
      org.auth: TRACE
      org.springframework.web: INFO
      org.springframework.security: INFO
      org.apache.tomcat.util.net: INFO
